"""Initial migration.

Revision ID: 008c38dac1d8
Revises: 
Create Date: 2024-05-12 21:02:11.394607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008c38dac1d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_data', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
